#ifndef GMPI_DRAWING_API_H_INCLUDED
#define GMPI_DRAWING_API_H_INCLUDED

// SPDX-License-Identifier: ISC
// Copyright 2007-2026 Jeff McClintock.

// Plain-C projection of the drawing API.
//
// The authoritative header is GmpiApiDrawing.h (gmpi::drawing::api). This file
// mirrors its vtables as C structs of function pointers - one slot per
// virtual, in declaration order, inherited methods flattened in first - so a C
// module calls the very same slots a C++ module does.
//
// THE VTABLE IS FROZEN (as of drawTextLayout). Keep this file in EXACT sync
// with GmpiApiDrawing.h: same methods, same order, same signatures, nothing
// added, nothing reordered. The shared layout is pinned by gmpi_ui_tests -
// drawing_abi_tests.cpp pins the C++ slots and c_projection_calls.c pins
// these structs, then calls a real backend through them. A failure there
// means the two headers no longer agree; this one is usually the stale one.
//
// HAND-MAINTAINED. This file was once generated by SynthEditLib/modules/
// se_sdk_gen from GMPI.xml, and that spec is now years stale - it still
// describes an IResource with no getFactory, which is what let this header
// drift a whole slot out of alignment and stay that way. Do not regenerate;
// edit by hand against GmpiApiDrawing.h and let the tests confirm it.

#include <math.h> // GMPI_linearToSRGB01

#include "gmpi.h" // GMPI/Projections/plain_c/Core

#pragma pack(push, 8)

enum GMPI_FontWeight
{
    GMPI_FONT_WEIGHT_THIN        = 100,
    GMPI_FONT_WEIGHT_EXTRA_LIGHT = 200,
    GMPI_FONT_WEIGHT_ULTRA_LIGHT = 200,
    GMPI_FONT_WEIGHT_LIGHT       = 300,
    GMPI_FONT_WEIGHT_NORMAL      = 400,
    GMPI_FONT_WEIGHT_REGULAR     = 400,
    GMPI_FONT_WEIGHT_MEDIUM      = 500,
    GMPI_FONT_WEIGHT_DEMI_BOLD   = 600,
    GMPI_FONT_WEIGHT_SEMI_BOLD   = 600,
    GMPI_FONT_WEIGHT_BOLD        = 700,
    GMPI_FONT_WEIGHT_EXTRA_BOLD  = 800,
    GMPI_FONT_WEIGHT_ULTRA_BOLD  = 800,
    GMPI_FONT_WEIGHT_BLACK       = 900,
    GMPI_FONT_WEIGHT_HEAVY       = 900,
    GMPI_FONT_WEIGHT_EXTRA_BLACK = 950,
    GMPI_FONT_WEIGHT_ULTRA_BLACK = 950,
};

enum GMPI_FontStretch
{
    GMPI_FONT_STRETCH_UNDEFINED       = 0,
    GMPI_FONT_STRETCH_ULTRA_CONDENSED = 1,
    GMPI_FONT_STRETCH_EXTRA_CONDENSED = 2,
    GMPI_FONT_STRETCH_CONDENSED       = 3,
    GMPI_FONT_STRETCH_SEMI_CONDENSED  = 4,
    GMPI_FONT_STRETCH_NORMAL          = 5,
    GMPI_FONT_STRETCH_MEDIUM          = 5,
    GMPI_FONT_STRETCH_SEMI_EXPANDED   = 6,
    GMPI_FONT_STRETCH_EXPANDED        = 7,
    GMPI_FONT_STRETCH_EXTRA_EXPANDED  = 8,
    GMPI_FONT_STRETCH_ULTRA_EXPANDED  = 9,
};

enum GMPI_FontStyle
{
    GMPI_FONT_STYLE_NORMAL  = 0,
    GMPI_FONT_STYLE_OBLIQUE = 1,
    GMPI_FONT_STYLE_ITALIC  = 2,
};

enum GMPI_FontFlags
{
    GMPI_FONT_FLAGS_BODY_HEIGHT   = 0, // height specifies the body-height of the font
    GMPI_FONT_FLAGS_CAP_HEIGHT    = 1, // height specifies the cap-height of the font
    GMPI_FONT_FLAGS_SYSTEM_HEIGHT = 2, // height is interpreted by the OS, results in uneven heights between different fonts.
};

enum GMPI_TextAlignment
{
    GMPI_TEXT_ALIGNMENT_LEADING  = 0,
    GMPI_TEXT_ALIGNMENT_LEFT     = 0,
    GMPI_TEXT_ALIGNMENT_TRAILING = 1,
    GMPI_TEXT_ALIGNMENT_RIGHT    = 1,
    GMPI_TEXT_ALIGNMENT_CENTER   = 2,
};

enum GMPI_ParagraphAlignment
{
    GMPI_PARAGRAPH_ALIGNMENT_NEAR   = 0,
    GMPI_PARAGRAPH_ALIGNMENT_TOP    = 0,
    GMPI_PARAGRAPH_ALIGNMENT_FAR    = 1,
    GMPI_PARAGRAPH_ALIGNMENT_BOTTOM = 1,
    GMPI_PARAGRAPH_ALIGNMENT_CENTER = 2,
};

enum GMPI_WordWrapping
{
    GMPI_WORD_WRAPPING_WRAP    = 0,
    GMPI_WORD_WRAPPING_NO_WRAP = 1,
};

enum GMPI_BitmapLockFlags
{
    GMPI_BITMAP_LOCK_FLAGS_READ = 1,
    GMPI_BITMAP_LOCK_FLAGS_WRITE,
    GMPI_BITMAP_LOCK_FLAGS_READ_WRITE,
};

enum GMPI_BitmapRenderTargetFlags
{
    GMPI_BITMAP_RENDER_TARGET_FLAGS_NONE         = 0,
    GMPI_BITMAP_RENDER_TARGET_FLAGS_MASK         = 1, // 8bpp alpha-only (1 byte per pixel). LINEAR coverage.
    GMPI_BITMAP_RENDER_TARGET_FLAGS_CPU_READABLE = 2,
    GMPI_BITMAP_RENDER_TARGET_FLAGS_SRGB_PIXELS  = 4, // sRGB, 8 bits per channel, 32bpp PBGRA
    // default (no format flag) = 64bppPRGBAHalf (half-float)
};
// These are FLAGS, and the combination matters:
//   SRGB_PIXELS alone is not enough to get an 8-bit face on DirectX - format
//   selection there is gated behind CPU_READABLE, so pass
//   SRGB_PIXELS | CPU_READABLE when you want bytes.
//   GMPI_IFactory.createCpuRenderTarget force-ORs CPU_READABLE for you; the
//   GMPI_IDeviceContext.createCompatibleRenderTarget route does not, and that
//   decides whether lockPixels() works.
// 8-bit COLOUR is sRGB-encoded, for a render target as well as for a loaded
// image. Only MASK (coverage) is linear.

enum GMPI_Gamma
{
    GMPI_GAMMA_2_2 = 0,
    GMPI_GAMMA_1_0 = 1,
};

enum GMPI_ExtendMode
{
    GMPI_EXTEND_MODE_CLAMP  = 0,
    GMPI_EXTEND_MODE_WRAP   = 1,
    GMPI_EXTEND_MODE_MIRROR = 2,
};

enum GMPI_BitmapInterpolationMode
{
    GMPI_BITMAP_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0,
    GMPI_BITMAP_INTERPOLATION_MODE_LINEAR           = 1,
};

// combinable bit flags
enum GMPI_DrawTextOptions
{
    GMPI_DRAW_TEXT_OPTIONS_NONE          = 0,
    GMPI_DRAW_TEXT_OPTIONS_NO_SNAP       = 1,
    GMPI_DRAW_TEXT_OPTIONS_CLIP          = 2,
    GMPI_DRAW_TEXT_OPTIONS_NO_MAC_SMOOTH = 4, // disable macOS native font smoothing (by default Mac uses its native smoothing)
};

enum GMPI_ArcSize
{
    GMPI_ARC_SIZE_SMALL = 0,
    GMPI_ARC_SIZE_LARGE = 1,
};

enum GMPI_CapStyle
{
    GMPI_CAP_STYLE_FLAT   = 0,
    GMPI_CAP_STYLE_SQUARE = 1,
    GMPI_CAP_STYLE_ROUND  = 2,
};

enum GMPI_DashStyle
{
    GMPI_DASH_STYLE_SOLID        = 0,
    GMPI_DASH_STYLE_DASH         = 1,
    GMPI_DASH_STYLE_DOT          = 2,
    GMPI_DASH_STYLE_DASH_DOT     = 3,
    GMPI_DASH_STYLE_DASH_DOT_DOT = 4,
    GMPI_DASH_STYLE_CUSTOM       = 5,
};

enum GMPI_LineJoin
{
    GMPI_LINE_JOIN_MITER          = 0,
    GMPI_LINE_JOIN_BEVEL          = 1,
    GMPI_LINE_JOIN_ROUND          = 2,
    GMPI_LINE_JOIN_MITER_OR_BEVEL = 3,
};

enum GMPI_FigureBegin
{
    GMPI_FIGURE_BEGIN_FILLED = 0,
    GMPI_FIGURE_BEGIN_HOLLOW = 1,
};

enum GMPI_FigureEnd
{
    GMPI_FIGURE_END_OPEN   = 0,
    GMPI_FIGURE_END_CLOSED = 1,
};

enum GMPI_PathSegment
{
    GMPI_PATH_SEGMENT_NONE                  = 0,
    GMPI_PATH_SEGMENT_FORCE_UNSTROKED       = 1,
    GMPI_PATH_SEGMENT_FORCE_ROUND_LINE_JOIN = 2,
};

enum GMPI_SweepDirection
{
    GMPI_SWEEP_DIRECTION_COUNTER_CLOCKWISE = 0,
    GMPI_SWEEP_DIRECTION_CLOCKWISE         = 1,
};

enum GMPI_FillMode
{
    GMPI_FILL_MODE_ALTERNATE = 0,
    GMPI_FILL_MODE_WINDING   = 1,
};

typedef struct GMPI_Color
{
    float r;
    float g;
    float b;
    float a;
} GMPI_Color;

typedef struct GMPI_Point
{
    float x;
    float y;
} GMPI_Point;

typedef struct GMPI_PointL
{
    int32_t x;
    int32_t y;
} GMPI_PointL;

typedef struct GMPI_Rect
{
    float left;
    float top;
    float right;
    float bottom;
} GMPI_Rect;

typedef struct GMPI_RectL
{
    int32_t left;
    int32_t top;
    int32_t right;
    int32_t bottom;
} GMPI_RectL;

typedef struct GMPI_Size
{
    float width;
    float height;
} GMPI_Size;

typedef struct GMPI_SizeU
{
    uint32_t width;
    uint32_t height;
} GMPI_SizeU;

typedef struct GMPI_SizeL
{
    int32_t width;
    int32_t height;
} GMPI_SizeL;

// Remember to initialise to identity (_11 = _22 = 1.0f), not all-zero.
typedef struct GMPI_Matrix3x2
{
    float _11;
    float _12;
    float _21;
    float _22;
    float _31;
    float _32;
} GMPI_Matrix3x2;

typedef struct GMPI_BitmapProperties
{
    float dpix;
    float dpiy;
} GMPI_BitmapProperties;

typedef struct GMPI_Gradientstop
{
    float position;
    GMPI_Color color;
} GMPI_Gradientstop;

// Remember to initialise opacity to 1.0f and transform to identity.
typedef struct GMPI_BrushProperties
{
    float opacity;
    GMPI_Matrix3x2 transform;
} GMPI_BrushProperties;

typedef struct GMPI_LinearGradientBrushProperties
{
    GMPI_Point startPoint;
    GMPI_Point endPoint;
} GMPI_LinearGradientBrushProperties;

typedef struct GMPI_RadialGradientBrushProperties
{
    GMPI_Point center;
    GMPI_Point gradientOriginOffset;
    float radiusX;
    float radiusY;
} GMPI_RadialGradientBrushProperties;

typedef struct GMPI_BezierSegment
{
    GMPI_Point point1;
    GMPI_Point point2;
    GMPI_Point point3;
} GMPI_BezierSegment;

typedef struct GMPI_Triangle
{
    GMPI_Point point1;
    GMPI_Point point2;
    GMPI_Point point3;
} GMPI_Triangle;

typedef struct GMPI_ArcSegment
{
    GMPI_Point point;
    GMPI_Size size;
    float rotationAngle;
    enum GMPI_SweepDirection sweepDirection;
    enum GMPI_ArcSize arcSize;
} GMPI_ArcSegment;

typedef struct GMPI_QuadraticBezierSegment
{
    GMPI_Point point1;
    GMPI_Point point2;
} GMPI_QuadraticBezierSegment;

typedef struct GMPI_Ellipse
{
    GMPI_Point point;
    float radiusX;
    float radiusY;
} GMPI_Ellipse;

typedef struct GMPI_RoundedRect
{
    GMPI_Rect rect;
    float radiusX;
    float radiusY;
} GMPI_RoundedRect;

// Notes:
// * GMPI_CAP_STYLE_FLAT is not recommended for dashed or dotted lines. It does not draw 'dots' on Windows.
// * miterLimit is customarily 10.0f.
typedef struct GMPI_StrokeStyleProperties
{
    enum GMPI_CapStyle lineCap;
    enum GMPI_LineJoin lineJoin;
    float miterLimit;
    enum GMPI_DashStyle dashStyle;
    float dashOffset;
} GMPI_StrokeStyleProperties;

typedef struct GMPI_FontMetrics
{
    float ascent;                // Distance from the top of the character alignment box to the English baseline.
    float descent;               // Distance from the bottom of the character alignment box to the English baseline.
    float lineGap;               // Recommended additional white space between lines. Recommended line spacing = ascent + descent + lineGap.
    float capHeight;             // Distance from the English baseline to the top of a typical English capital.
    float xHeight;               // Distance from the English baseline to the top of lowercase letter x.
    float underlinePosition;     // Position of underline relative to the English baseline (usually negative).
    float underlineThickness;
    float strikethroughPosition; // Position of strikethrough relative to the English baseline (usually positive).
    float strikethroughThickness;
} GMPI_FontMetrics;

// The sRGB transfer function, encode direction (IEC 61966-2-1), on [0,1].
// The same single definition as gmpi::drawing::linearToSRGB01 - every path
// that leaves the library's linear surfaces for an 8-bit consumer applies
// exactly this curve.
static inline float GMPI_linearToSRGB01(float c)
{
    c = c < 0.0f ? 0.0f : (c > 1.0f ? 1.0f : c);
    return (c <= 0.0031308f) ? c * 12.92f
                             : 1.055f * powf(c, 1.0f / 2.4f) - 0.055f;
}

// The character alignment box: ascent + descent, EXCLUDING lineGap.
// (OS/2 typo metrics when fsSelection bit 7 is set, Win metrics otherwise -
// see GmpiApiDrawing.h calcBodyHeight for why it is specifically not hhea.)
static inline float GMPI_calcBodyHeight(const GMPI_FontMetrics* fm)
{
    return fm->ascent + fm->descent;
}

// Which parts of a GMPI_TextStyleRun are active. EVERY override is opt-in, so
// an all-zero run is a valid no-op that inherits the base format entirely.
enum GMPI_TextStyleFlags
{
    GMPI_TEXT_STYLE_FLAGS_UNDERLINE       = 1,
    GMPI_TEXT_STYLE_FLAGS_STRIKETHROUGH   = 2,
    GMPI_TEXT_STYLE_FLAGS_HAS_COLOR       = 4,  // run.color overrides the draw call's brush
    GMPI_TEXT_STYLE_FLAGS_HAS_FONT_SIZE   = 8,  // run.fontSizeScale multiplies the base size
    GMPI_TEXT_STYLE_FLAGS_HAS_FONT_FAMILY = 16, // run.fontFamilyIndex selects a run family
    GMPI_TEXT_STYLE_FLAGS_HAS_FONT_WEIGHT = 32, // run.fontWeight overrides the base weight
    GMPI_TEXT_STYLE_FLAGS_HAS_FONT_STYLE  = 64, // run.fontStyle overrides the base style
};

// One styling run over the UTF-8 text of a GMPI_ITextLayout, resolved at creation.
//
// FROZEN: this struct crosses the ABI boundary and carries no size or version
// field, so no member can ever be added compatibly. Extensions arrive as new
// factory methods, never as new fields.
typedef struct GMPI_TextStyleRun
{
    int32_t begin;             // byte offset into the utf8 string; must land on
    int32_t length;            // a codepoint boundary. Runs must be sorted,
                               // non-overlapping and in-bounds, else creation fails.
    int32_t flags;             // GMPI_TextStyleFlags bitmask
    enum GMPI_FontWeight fontWeight; // honoured when HAS_FONT_WEIGHT
    enum GMPI_FontStyle fontStyle;   // honoured when HAS_FONT_STYLE
    GMPI_Color color;          // honoured when HAS_COLOR
    float fontSizeScale;       // multiplier of the base format's RESOLVED size,
                               // honoured when HAS_FONT_SIZE. A scale, not DIPs.
    int32_t fontFamilyIndex;   // into createTextLayout's runFamilies, honoured
                               // when HAS_FONT_FAMILY
} GMPI_TextStyleRun;

// Interfaces reference each other, so declare them all up front.
typedef struct GMPI_ITextFormat             GMPI_ITextFormat;
typedef struct GMPI_IRichTextFormat         GMPI_IRichTextFormat;
typedef struct GMPI_ITextLayout             GMPI_ITextLayout;
typedef struct GMPI_IResource               GMPI_IResource;
typedef struct GMPI_IBitmapPixels           GMPI_IBitmapPixels;
typedef struct GMPI_IBitmap                 GMPI_IBitmap;
typedef struct GMPI_IGradientstopCollection GMPI_IGradientstopCollection;
typedef struct GMPI_IBrush                  GMPI_IBrush;
typedef struct GMPI_IBitmapBrush            GMPI_IBitmapBrush;
typedef struct GMPI_ISolidColorBrush        GMPI_ISolidColorBrush;
typedef struct GMPI_ILinearGradientBrush    GMPI_ILinearGradientBrush;
typedef struct GMPI_IRadialGradientBrush    GMPI_IRadialGradientBrush;
typedef struct GMPI_IStrokeStyle            GMPI_IStrokeStyle;
typedef struct GMPI_IGeometrySink           GMPI_IGeometrySink;
typedef struct GMPI_IPathGeometry           GMPI_IPathGeometry;
typedef struct GMPI_IDeviceContext          GMPI_IDeviceContext;
typedef struct GMPI_IBitmapRenderTarget     GMPI_IBitmapRenderTarget;
typedef struct GMPI_IFactory                GMPI_IFactory;

// INTERFACE 'GMPI_ITextFormat' (gmpi::drawing::api::ITextFormat)
struct GMPI_ITextFormat
{
    struct GMPI_ITextFormatMethods* methods;
};

typedef struct GMPI_ITextFormatMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    int32_t (*setTextAlignment)(GMPI_ITextFormat*, int32_t textAlignment);           // GMPI_TextAlignment
    int32_t (*setParagraphAlignment)(GMPI_ITextFormat*, int32_t paragraphAlignment); // GMPI_ParagraphAlignment
    int32_t (*setWordWrapping)(GMPI_ITextFormat*, int32_t wordWrapping);             // GMPI_WordWrapping
    int32_t (*getTextExtentU)(GMPI_ITextFormat*, const char* utf8String, int32_t stringLength, float maxWidth, GMPI_Size* returnSize);
    int32_t (*getFontMetrics)(GMPI_ITextFormat*, GMPI_FontMetrics* returnFontMetrics);
    // For the default method use lineSpacing=-1 (spacing depends solely on the content). For uniform spacing, the specified line height overrides the content.
    int32_t (*setLineSpacing)(GMPI_ITextFormat*, float lineSpacing, float baseline);
} GMPI_ITextFormatMethods;

// {ED903255-3FE0-4CE4-8CD1-97D72D51B7CB}
static const GMPI_Guid GMPI_IID_TEXT_FORMAT =
{ 0xED903255, 0x3FE0, 0x4CE4, { 0x8C, 0xD1, 0x97, 0xD7, 0x2D, 0x51, 0xB7, 0xCB} };

// INTERFACE 'GMPI_IRichTextFormat' (gmpi::drawing::api::IRichTextFormat)
// Immutable formatted text layout created from a markdown string.
// All formatting is determined at creation time.
struct GMPI_IRichTextFormat
{
    struct GMPI_IRichTextFormatMethods* methods;
};

typedef struct GMPI_IRichTextFormatMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    int32_t (*getTextExtentU)(GMPI_IRichTextFormat*, GMPI_Size* returnSize);
} GMPI_IRichTextFormatMethods;

// {A3B8F4C1-7E2D-4A5F-9C6E-1D8B3F5A2E47}
static const GMPI_Guid GMPI_IID_RICH_TEXT_FORMAT =
{ 0xA3B8F4C1, 0x7E2D, 0x4A5F, { 0x9C, 0x6E, 0x1D, 0x8B, 0x3F, 0x5A, 0x2E, 0x47} };

// INTERFACE 'GMPI_ITextLayout' (gmpi::drawing::api::ITextLayout)
// An immutable, retained text layout: the text, its styling runs, the layout
// box, alignment and spacing are ALL fixed at creation.
// Single-threaded use, like every other drawing object here.
struct GMPI_ITextLayout
{
    struct GMPI_ITextLayoutMethods* methods;
};

typedef struct GMPI_ITextLayoutMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    // The same value GMPI_ITextFormat.getTextExtentU returns for this text at
    // the layout's maxWidth: tight bounds of the formatted text, independent
    // of alignment. Measured once at creation, never re-measured.
    int32_t (*getTextExtentU)(GMPI_ITextLayout*, GMPI_Size* returnSize);
} GMPI_ITextLayoutMethods;

// {6D2A9E74-5C31-4B88-A0F2-3E7C1B4D8A59}
static const GMPI_Guid GMPI_IID_TEXT_LAYOUT =
{ 0x6D2A9E74, 0x5C31, 0x4B88, { 0xA0, 0xF2, 0x3E, 0x7C, 0x1B, 0x4D, 0x8A, 0x59} };

// INTERFACE 'GMPI_IResource' (gmpi::drawing::api::IResource)
struct GMPI_IResource
{
    struct GMPI_IResourceMethods* methods;
};

typedef struct GMPI_IResourceMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    int32_t (*getFactory)(GMPI_IResource*, GMPI_IFactory** returnFactory);
} GMPI_IResourceMethods;

// {617750C9-14DC-4157-BBD0-FEDF5270D8FD}
static const GMPI_Guid GMPI_IID_RESOURCE =
{ 0x617750C9, 0x14DC, 0x4157, { 0xBB, 0xD0, 0xFE, 0xDF, 0x52, 0x70, 0xD8, 0xFD} };

// Bit-encoded pixel format (gmpi::drawing::api::IBitmapPixels::PixelFormat):
//   [7:0]  bytes per pixel
//   [8]    1 = integer, 0 = float
//   [10:9] channel layout: 0=BGRA, 1=RGBA, 2=ARGB, 3=ABGR
//   [11]   1 = sRGB transfer function, 0 = linear
//
// Read these bits rather than assuming, and read ALL of them:
//   * bytes-per-pixel comes from bits [7:0], NOT from bytesPerRow / width.
//     Rows can be padded, so that division silently reports the wrong stride.
//   * channel layout comes from [10:9], NOT from #ifdef _WIN32. Backends do
//     not agree.
//   * the transfer function comes from [11] and means what it says.
//     Everything 8-bit and colour is sRGB-encoded; only ALPHA_8I coverage is
//     linear.
enum GMPI_PixelFormat
{
    // Linear float
    GMPI_PIXEL_FORMAT_RGBA_32F     = 16 | (1 << 9),                       // macOS 128bpp float
    GMPI_PIXEL_FORMAT_RGBA_16F     = 8 | (1 << 9),                        // Windows 64bpp half-float
    // Linear integer
    GMPI_PIXEL_FORMAT_RGBA_16I     = 8 | (1 << 8) | (1 << 9),             // macOS 64bpp uint16
    GMPI_PIXEL_FORMAT_ALPHA_8I     = 1 | (1 << 8),                        // 8bpp alpha mask
    // sRGB integer
    GMPI_PIXEL_FORMAT_BGRA_SRGB_8I = 4 | (1 << 8) | (1 << 11),            // Windows 32bpp sRGB
    GMPI_PIXEL_FORMAT_RGBA_SRGB_8I = 4 | (1 << 8) | (1 << 9) | (1 << 11), // macOS 32bpp sRGB
};

// INTERFACE 'GMPI_IBitmapPixels' (gmpi::drawing::api::IBitmapPixels)
struct GMPI_IBitmapPixels
{
    struct GMPI_IBitmapPixelsMethods* methods;
};

typedef struct GMPI_IBitmapPixelsMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    int32_t (*getAddress)(GMPI_IBitmapPixels*, uint8_t** returnAddress);
    int32_t (*getBytesPerRow)(GMPI_IBitmapPixels*, int32_t* returnBytesPerRow);
    int32_t (*getPixelFormat)(GMPI_IBitmapPixels*, int32_t* returnPixelFormat); // GMPI_PixelFormat
} GMPI_IBitmapPixelsMethods;

// {CCE4F628-289E-4EAB-9837-1755D9E5F793}
static const GMPI_Guid GMPI_IID_BITMAP_PIXELS =
{ 0xCCE4F628, 0x289E, 0x4EAB, { 0x98, 0x37, 0x17, 0x55, 0xD9, 0xE5, 0xF7, 0x93} };

// INTERFACE 'GMPI_IBitmap' (gmpi::drawing::api::IBitmap : IResource)
struct GMPI_IBitmap
{
    struct GMPI_IBitmapMethods* methods;
};

typedef struct GMPI_IBitmapMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    // Methods of GMPI_IResource
    int32_t (*getFactory)(GMPI_IBitmap*, GMPI_IFactory** returnFactory);

    int32_t (*getSizeU)(GMPI_IBitmap*, GMPI_SizeU* returnSizeU);
    // Note: Not supported when Bitmap was created on GPU
    int32_t (*lockPixels)(GMPI_IBitmap*, GMPI_IBitmapPixels** returnPixels, int32_t flags); // GMPI_BitmapLockFlags
} GMPI_IBitmapMethods;

// {EDF250B7-29FE-4FEC-8C6A-FBCB1F0A301A}
static const GMPI_Guid GMPI_IID_BITMAP =
{ 0xEDF250B7, 0x29FE, 0x4FEC, { 0x8C, 0x6A, 0xFB, 0xCB, 0x1F, 0x0A, 0x30, 0x1A} };

// INTERFACE 'GMPI_IGradientstopCollection' (gmpi::drawing::api::IGradientstopCollection : IResource)
struct GMPI_IGradientstopCollection
{
    struct GMPI_IGradientstopCollectionMethods* methods;
};

typedef struct GMPI_IGradientstopCollectionMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    // Methods of GMPI_IResource
    int32_t (*getFactory)(GMPI_IGradientstopCollection*, GMPI_IFactory** returnFactory);
} GMPI_IGradientstopCollectionMethods;

// {AEE31225-BFF4-42DE-B8CA-233C5A3441CB}
static const GMPI_Guid GMPI_IID_GRADIENTSTOP_COLLECTION =
{ 0xAEE31225, 0xBFF4, 0x42DE, { 0xB8, 0xCA, 0x23, 0x3C, 0x5A, 0x34, 0x41, 0xCB} };

// INTERFACE 'GMPI_IBrush' (gmpi::drawing::api::IBrush : IResource, no methods, no IID of its own)
struct GMPI_IBrush
{
    struct GMPI_IBrushMethods* methods;
};

typedef struct GMPI_IBrushMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    // Methods of GMPI_IResource
    int32_t (*getFactory)(GMPI_IBrush*, GMPI_IFactory** returnFactory);
} GMPI_IBrushMethods;

// INTERFACE 'GMPI_IBitmapBrush' (gmpi::drawing::api::IBitmapBrush : IBrush)
struct GMPI_IBitmapBrush
{
    struct GMPI_IBitmapBrushMethods* methods;
};

typedef struct GMPI_IBitmapBrushMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    // Methods of GMPI_IResource
    int32_t (*getFactory)(GMPI_IBitmapBrush*, GMPI_IFactory** returnFactory);
} GMPI_IBitmapBrushMethods;

// {10E6068D-75D7-4C36-89AD-1C8878E70988}
static const GMPI_Guid GMPI_IID_BITMAP_BRUSH =
{ 0x10E6068D, 0x75D7, 0x4C36, { 0x89, 0xAD, 0x1C, 0x88, 0x78, 0xE7, 0x09, 0x88} };

// INTERFACE 'GMPI_ISolidColorBrush' (gmpi::drawing::api::ISolidColorBrush : IBrush)
struct GMPI_ISolidColorBrush
{
    struct GMPI_ISolidColorBrushMethods* methods;
};

typedef struct GMPI_ISolidColorBrushMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    // Methods of GMPI_IResource
    int32_t (*getFactory)(GMPI_ISolidColorBrush*, GMPI_IFactory** returnFactory);

    void (*setColor)(GMPI_ISolidColorBrush*, const GMPI_Color* color);
} GMPI_ISolidColorBrushMethods;

// {BB3FD251-47A0-4273-90AB-A5CDC88F57B9}
static const GMPI_Guid GMPI_IID_SOLID_COLOR_BRUSH =
{ 0xBB3FD251, 0x47A0, 0x4273, { 0x90, 0xAB, 0xA5, 0xCD, 0xC8, 0x8F, 0x57, 0xB9} };

// INTERFACE 'GMPI_ILinearGradientBrush' (gmpi::drawing::api::ILinearGradientBrush : IBrush)
struct GMPI_ILinearGradientBrush
{
    struct GMPI_ILinearGradientBrushMethods* methods;
};

typedef struct GMPI_ILinearGradientBrushMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    // Methods of GMPI_IResource
    int32_t (*getFactory)(GMPI_ILinearGradientBrush*, GMPI_IFactory** returnFactory);

    void (*setStartPoint)(GMPI_ILinearGradientBrush*, GMPI_Point startPoint);
    void (*setEndPoint)(GMPI_ILinearGradientBrush*, GMPI_Point endPoint);
} GMPI_ILinearGradientBrushMethods;

// {986C3B9A-9D0A-4BF5-B721-0B9611B2798D}
static const GMPI_Guid GMPI_IID_LINEAR_GRADIENT_BRUSH =
{ 0x986C3B9A, 0x9D0A, 0x4BF5, { 0xB7, 0x21, 0x0B, 0x96, 0x11, 0xB2, 0x79, 0x8D} };

// INTERFACE 'GMPI_IRadialGradientBrush' (gmpi::drawing::api::IRadialGradientBrush : IBrush)
struct GMPI_IRadialGradientBrush
{
    struct GMPI_IRadialGradientBrushMethods* methods;
};

typedef struct GMPI_IRadialGradientBrushMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    // Methods of GMPI_IResource
    int32_t (*getFactory)(GMPI_IRadialGradientBrush*, GMPI_IFactory** returnFactory);

    void (*setCenter)(GMPI_IRadialGradientBrush*, GMPI_Point center);
    void (*setGradientOriginOffset)(GMPI_IRadialGradientBrush*, GMPI_Point gradientOriginOffset);
    void (*setRadiusX)(GMPI_IRadialGradientBrush*, float radiusX);
    void (*setRadiusY)(GMPI_IRadialGradientBrush*, float radiusY);
} GMPI_IRadialGradientBrushMethods;

// {A3436B5B-C3F7-4A27-9BD9-710D653EE560}
static const GMPI_Guid GMPI_IID_RADIAL_GRADIENT_BRUSH =
{ 0xA3436B5B, 0xC3F7, 0x4A27, { 0x9B, 0xD9, 0x71, 0x0D, 0x65, 0x3E, 0xE5, 0x60} };

// INTERFACE 'GMPI_IStrokeStyle' (gmpi::drawing::api::IStrokeStyle : IResource)
struct GMPI_IStrokeStyle
{
    struct GMPI_IStrokeStyleMethods* methods;
};

typedef struct GMPI_IStrokeStyleMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    // Methods of GMPI_IResource
    int32_t (*getFactory)(GMPI_IStrokeStyle*, GMPI_IFactory** returnFactory);
} GMPI_IStrokeStyleMethods;

// {27D19BF3-9DB2-49CC-A8EE-28E0716EA8B6}
static const GMPI_Guid GMPI_IID_STROKE_STYLE =
{ 0x27D19BF3, 0x9DB2, 0x49CC, { 0xA8, 0xEE, 0x28, 0xE0, 0x71, 0x6E, 0xA8, 0xB6} };

// INTERFACE 'GMPI_IGeometrySink' (gmpi::drawing::api::IGeometrySink)
struct GMPI_IGeometrySink
{
    struct GMPI_IGeometrySinkMethods* methods;
};

typedef struct GMPI_IGeometrySinkMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    void (*beginFigure)(GMPI_IGeometrySink*, GMPI_Point startPoint, int32_t figureBegin); // GMPI_FigureBegin
    void (*endFigure)(GMPI_IGeometrySink*, int32_t figureEnd);                            // GMPI_FigureEnd
    void (*setFillMode)(GMPI_IGeometrySink*, int32_t fillMode);                           // GMPI_FillMode
    int32_t (*close)(GMPI_IGeometrySink*);
    void (*addLine)(GMPI_IGeometrySink*, GMPI_Point point);
    void (*addLines)(GMPI_IGeometrySink*, const GMPI_Point* points, uint32_t pointsCount);
    void (*addBezier)(GMPI_IGeometrySink*, const GMPI_BezierSegment* bezier);
    void (*addBeziers)(GMPI_IGeometrySink*, const GMPI_BezierSegment* beziers, uint32_t beziersCount);
    void (*addQuadraticBezier)(GMPI_IGeometrySink*, const GMPI_QuadraticBezierSegment* bezier);
    void (*addQuadraticBeziers)(GMPI_IGeometrySink*, const GMPI_QuadraticBezierSegment* beziers, uint32_t beziersCount);
    void (*addArc)(GMPI_IGeometrySink*, const GMPI_ArcSegment* arc);
} GMPI_IGeometrySinkMethods;

// {A935E374-8F14-4824-A5CB-58287E994193}
static const GMPI_Guid GMPI_IID_GEOMETRY_SINK =
{ 0xA935E374, 0x8F14, 0x4824, { 0xA5, 0xCB, 0x58, 0x28, 0x7E, 0x99, 0x41, 0x93} };

// INTERFACE 'GMPI_IPathGeometry' (gmpi::drawing::api::IPathGeometry : IResource)
struct GMPI_IPathGeometry
{
    struct GMPI_IPathGeometryMethods* methods;
};

typedef struct GMPI_IPathGeometryMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    // Methods of GMPI_IResource
    int32_t (*getFactory)(GMPI_IPathGeometry*, GMPI_IFactory** returnFactory);

    int32_t (*open)(GMPI_IPathGeometry*, GMPI_IGeometrySink** returnGeometrySink);
    // in DX, these are part of IMpGeometry. But were added later here, and so added last. not a big deal since we support only one type of geometry, not many like DX.
    int32_t (*strokeContainsPoint)(GMPI_IPathGeometry*, GMPI_Point point, float strokeWidth, GMPI_IStrokeStyle* strokeStyle, const GMPI_Matrix3x2* worldTransform, bool* returnContains);
    int32_t (*fillContainsPoint)(GMPI_IPathGeometry*, GMPI_Point point, const GMPI_Matrix3x2* worldTransform, bool* returnContains);
    int32_t (*getWidenedBounds)(GMPI_IPathGeometry*, float strokeWidth, GMPI_IStrokeStyle* strokeStyle, const GMPI_Matrix3x2* worldTransform, GMPI_Rect* returnBounds);
} GMPI_IPathGeometryMethods;

// {89C6E868-B8A5-49BF-B771-02FB1EEF38AD}
static const GMPI_Guid GMPI_IID_PATH_GEOMETRY =
{ 0x89C6E868, 0xB8A5, 0x49BF, { 0xB7, 0x71, 0x02, 0xFB, 0x1E, 0xEF, 0x38, 0xAD} };

// INTERFACE 'GMPI_IDeviceContext' (gmpi::drawing::api::IDeviceContext : IResource)
struct GMPI_IDeviceContext
{
    struct GMPI_IDeviceContextMethods* methods;
};

typedef struct GMPI_IDeviceContextMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    // Methods of GMPI_IResource
    int32_t (*getFactory)(GMPI_IDeviceContext*, GMPI_IFactory** returnFactory);

    int32_t (*createBitmapBrush)(GMPI_IDeviceContext*, GMPI_IBitmap* bitmap, const GMPI_BrushProperties* brushProperties, GMPI_IBitmapBrush** returnBitmapBrush);
    int32_t (*createSolidColorBrush)(GMPI_IDeviceContext*, const GMPI_Color* color, const GMPI_BrushProperties* brushProperties, GMPI_ISolidColorBrush** returnSolidColorBrush);
    int32_t (*createGradientstopCollection)(GMPI_IDeviceContext*, const GMPI_Gradientstop* gradientstops, uint32_t gradientstopsCount, int32_t extendMode, GMPI_IGradientstopCollection** returnGradientstopCollection); // GMPI_ExtendMode
    int32_t (*createLinearGradientBrush)(GMPI_IDeviceContext*, const GMPI_LinearGradientBrushProperties* linearGradientBrushProperties, const GMPI_BrushProperties* brushProperties, GMPI_IGradientstopCollection* gradientstopCollection, GMPI_ILinearGradientBrush** returnLinearGradientBrush);
    int32_t (*createRadialGradientBrush)(GMPI_IDeviceContext*, const GMPI_RadialGradientBrushProperties* radialGradientBrushProperties, const GMPI_BrushProperties* brushProperties, GMPI_IGradientstopCollection* gradientstopCollection, GMPI_IRadialGradientBrush** returnRadialGradientBrush);
    int32_t (*drawLine)(GMPI_IDeviceContext*, GMPI_Point point0, GMPI_Point point1, GMPI_IBrush* brush, float strokeWidth, GMPI_IStrokeStyle* strokeStyle);
    int32_t (*drawRectangle)(GMPI_IDeviceContext*, const GMPI_Rect* rect, GMPI_IBrush* brush, float strokeWidth, GMPI_IStrokeStyle* strokeStyle);
    int32_t (*fillRectangle)(GMPI_IDeviceContext*, const GMPI_Rect* rect, GMPI_IBrush* brush);
    int32_t (*drawRoundedRectangle)(GMPI_IDeviceContext*, const GMPI_RoundedRect* roundedRect, GMPI_IBrush* brush, float strokeWidth, GMPI_IStrokeStyle* strokeStyle);
    int32_t (*fillRoundedRectangle)(GMPI_IDeviceContext*, const GMPI_RoundedRect* roundedRect, GMPI_IBrush* brush);
    int32_t (*drawEllipse)(GMPI_IDeviceContext*, const GMPI_Ellipse* ellipse, GMPI_IBrush* brush, float strokeWidth, GMPI_IStrokeStyle* strokeStyle);
    int32_t (*fillEllipse)(GMPI_IDeviceContext*, const GMPI_Ellipse* ellipse, GMPI_IBrush* brush);
    int32_t (*drawGeometry)(GMPI_IDeviceContext*, GMPI_IPathGeometry* pathGeometry, GMPI_IBrush* brush, float strokeWidth, GMPI_IStrokeStyle* strokeStyle);
    int32_t (*fillGeometry)(GMPI_IDeviceContext*, GMPI_IPathGeometry* pathGeometry, GMPI_IBrush* brush, GMPI_IBrush* opacityBrush);
    int32_t (*drawBitmap)(GMPI_IDeviceContext*, GMPI_IBitmap* bitmap, const GMPI_Rect* destinationRectangle, float opacity, int32_t interpolationMode, const GMPI_Rect* sourceRectangle); // GMPI_BitmapInterpolationMode
    int32_t (*drawTextU)(GMPI_IDeviceContext*, const char* string, uint32_t stringLength, GMPI_ITextFormat* textFormat, const GMPI_Rect* layoutRect, GMPI_IBrush* defaultForegroundBrush, int32_t options); // GMPI_DrawTextOptions
    int32_t (*drawRichTextU)(GMPI_IDeviceContext*, GMPI_IRichTextFormat* richTextFormat, const GMPI_Rect* layoutRect, GMPI_IBrush* defaultForegroundBrush, int32_t options); // GMPI_DrawTextOptions
    int32_t (*setTransform)(GMPI_IDeviceContext*, const GMPI_Matrix3x2* transform);
    int32_t (*getTransform)(GMPI_IDeviceContext*, GMPI_Matrix3x2* returnTransform);
    int32_t (*pushAxisAlignedClip)(GMPI_IDeviceContext*, const GMPI_Rect* clipRect);
    int32_t (*popAxisAlignedClip)(GMPI_IDeviceContext*);
    int32_t (*getAxisAlignedClip)(GMPI_IDeviceContext*, GMPI_Rect* returnClipRect);
    int32_t (*clear)(GMPI_IDeviceContext*, const GMPI_Color* clearColor);
    int32_t (*beginDraw)(GMPI_IDeviceContext*);
    int32_t (*endDraw)(GMPI_IDeviceContext*);
    int32_t (*createCompatibleRenderTarget)(GMPI_IDeviceContext*, GMPI_Size desiredSize, int32_t flags, GMPI_IBitmapRenderTarget** returnBitmapRenderTarget); // flags: GMPI_BitmapRenderTargetFlags
    // ---------------------------------------------------------------------
    // WARNING - appending here is NOT binary compatible.
    //
    // GMPI_IBitmapRenderTarget (below) derives from GMPI_IDeviceContext, so
    // its own method, getBitmap, sits immediately AFTER the last method
    // declared here. Every method appended here pushes getBitmap one slot
    // further down, and any GUI module compiled against an older copy of this
    // header calls the newly appended method where it means to call getBitmap
    // - a jump into the wrong function with the wrong arguments.
    //
    // The policy is: do not break the vtable. The two methods below are a
    // deliberate exception taken twice during beta, not a precedent. See the
    // matching warning in GmpiApiDrawing.h - and remember this file may only
    // ever mirror that one, never lead it.
    // ---------------------------------------------------------------------

    // Intersect the current clip region with an arbitrary geometry.
    // Release it with popAxisAlignedClip(), exactly like a rectangular clip.
    int32_t (*pushClipGeometry)(GMPI_IDeviceContext*, GMPI_IPathGeometry* geometry);

    // Draw a retained layout at `point` - a GMPI_Point, not a GMPI_Rect,
    // because the layout owns its box. Text exceeding that box is still laid
    // out against it and DRAWN; GMPI_DRAW_TEXT_OPTIONS_CLIP clips exactly as
    // drawTextU's would for the equivalent rect.
    //
    // Runs without GMPI_TEXT_STYLE_FLAGS_HAS_COLOR fill with
    // defaultForegroundBrush, so a cached layout can be re-tinted per draw
    // (hover, selection) without being rebuilt.
    int32_t (*drawTextLayout)(GMPI_IDeviceContext*, GMPI_Point point, GMPI_ITextLayout* textLayout, GMPI_IBrush* defaultForegroundBrush, int32_t options); // GMPI_DrawTextOptions
} GMPI_IDeviceContextMethods;

// {F38EC187-BA04-4A63-B1D6-22D931E1F308}
static const GMPI_Guid GMPI_IID_DEVICE_CONTEXT =
{ 0xF38EC187, 0xBA04, 0x4A63, { 0xB1, 0xD6, 0x22, 0xD9, 0x31, 0xE1, 0xF3, 0x08} };

// INTERFACE 'GMPI_IBitmapRenderTarget' (gmpi::drawing::api::IBitmapRenderTarget : IDeviceContext)
//
// The full GMPI_IDeviceContext method table, flattened, then getBitmap.
// getBitmap is the 33rd slot (index 32, byte offset 32 * sizeof(void*)) -
// the exact slot the frozen-vtable policy above exists to protect.
struct GMPI_IBitmapRenderTarget
{
    struct GMPI_IBitmapRenderTargetMethods* methods;
};

typedef struct GMPI_IBitmapRenderTargetMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    // Methods of GMPI_IResource
    int32_t (*getFactory)(GMPI_IBitmapRenderTarget*, GMPI_IFactory** returnFactory);

    // Methods of GMPI_IDeviceContext
    int32_t (*createBitmapBrush)(GMPI_IBitmapRenderTarget*, GMPI_IBitmap* bitmap, const GMPI_BrushProperties* brushProperties, GMPI_IBitmapBrush** returnBitmapBrush);
    int32_t (*createSolidColorBrush)(GMPI_IBitmapRenderTarget*, const GMPI_Color* color, const GMPI_BrushProperties* brushProperties, GMPI_ISolidColorBrush** returnSolidColorBrush);
    int32_t (*createGradientstopCollection)(GMPI_IBitmapRenderTarget*, const GMPI_Gradientstop* gradientstops, uint32_t gradientstopsCount, int32_t extendMode, GMPI_IGradientstopCollection** returnGradientstopCollection); // GMPI_ExtendMode
    int32_t (*createLinearGradientBrush)(GMPI_IBitmapRenderTarget*, const GMPI_LinearGradientBrushProperties* linearGradientBrushProperties, const GMPI_BrushProperties* brushProperties, GMPI_IGradientstopCollection* gradientstopCollection, GMPI_ILinearGradientBrush** returnLinearGradientBrush);
    int32_t (*createRadialGradientBrush)(GMPI_IBitmapRenderTarget*, const GMPI_RadialGradientBrushProperties* radialGradientBrushProperties, const GMPI_BrushProperties* brushProperties, GMPI_IGradientstopCollection* gradientstopCollection, GMPI_IRadialGradientBrush** returnRadialGradientBrush);
    int32_t (*drawLine)(GMPI_IBitmapRenderTarget*, GMPI_Point point0, GMPI_Point point1, GMPI_IBrush* brush, float strokeWidth, GMPI_IStrokeStyle* strokeStyle);
    int32_t (*drawRectangle)(GMPI_IBitmapRenderTarget*, const GMPI_Rect* rect, GMPI_IBrush* brush, float strokeWidth, GMPI_IStrokeStyle* strokeStyle);
    int32_t (*fillRectangle)(GMPI_IBitmapRenderTarget*, const GMPI_Rect* rect, GMPI_IBrush* brush);
    int32_t (*drawRoundedRectangle)(GMPI_IBitmapRenderTarget*, const GMPI_RoundedRect* roundedRect, GMPI_IBrush* brush, float strokeWidth, GMPI_IStrokeStyle* strokeStyle);
    int32_t (*fillRoundedRectangle)(GMPI_IBitmapRenderTarget*, const GMPI_RoundedRect* roundedRect, GMPI_IBrush* brush);
    int32_t (*drawEllipse)(GMPI_IBitmapRenderTarget*, const GMPI_Ellipse* ellipse, GMPI_IBrush* brush, float strokeWidth, GMPI_IStrokeStyle* strokeStyle);
    int32_t (*fillEllipse)(GMPI_IBitmapRenderTarget*, const GMPI_Ellipse* ellipse, GMPI_IBrush* brush);
    int32_t (*drawGeometry)(GMPI_IBitmapRenderTarget*, GMPI_IPathGeometry* pathGeometry, GMPI_IBrush* brush, float strokeWidth, GMPI_IStrokeStyle* strokeStyle);
    int32_t (*fillGeometry)(GMPI_IBitmapRenderTarget*, GMPI_IPathGeometry* pathGeometry, GMPI_IBrush* brush, GMPI_IBrush* opacityBrush);
    int32_t (*drawBitmap)(GMPI_IBitmapRenderTarget*, GMPI_IBitmap* bitmap, const GMPI_Rect* destinationRectangle, float opacity, int32_t interpolationMode, const GMPI_Rect* sourceRectangle); // GMPI_BitmapInterpolationMode
    int32_t (*drawTextU)(GMPI_IBitmapRenderTarget*, const char* string, uint32_t stringLength, GMPI_ITextFormat* textFormat, const GMPI_Rect* layoutRect, GMPI_IBrush* defaultForegroundBrush, int32_t options); // GMPI_DrawTextOptions
    int32_t (*drawRichTextU)(GMPI_IBitmapRenderTarget*, GMPI_IRichTextFormat* richTextFormat, const GMPI_Rect* layoutRect, GMPI_IBrush* defaultForegroundBrush, int32_t options); // GMPI_DrawTextOptions
    int32_t (*setTransform)(GMPI_IBitmapRenderTarget*, const GMPI_Matrix3x2* transform);
    int32_t (*getTransform)(GMPI_IBitmapRenderTarget*, GMPI_Matrix3x2* returnTransform);
    int32_t (*pushAxisAlignedClip)(GMPI_IBitmapRenderTarget*, const GMPI_Rect* clipRect);
    int32_t (*popAxisAlignedClip)(GMPI_IBitmapRenderTarget*);
    int32_t (*getAxisAlignedClip)(GMPI_IBitmapRenderTarget*, GMPI_Rect* returnClipRect);
    int32_t (*clear)(GMPI_IBitmapRenderTarget*, const GMPI_Color* clearColor);
    int32_t (*beginDraw)(GMPI_IBitmapRenderTarget*);
    int32_t (*endDraw)(GMPI_IBitmapRenderTarget*);
    int32_t (*createCompatibleRenderTarget)(GMPI_IBitmapRenderTarget*, GMPI_Size desiredSize, int32_t flags, GMPI_IBitmapRenderTarget** returnBitmapRenderTarget); // flags: GMPI_BitmapRenderTargetFlags
    int32_t (*pushClipGeometry)(GMPI_IBitmapRenderTarget*, GMPI_IPathGeometry* geometry);
    int32_t (*drawTextLayout)(GMPI_IBitmapRenderTarget*, GMPI_Point point, GMPI_ITextLayout* textLayout, GMPI_IBrush* defaultForegroundBrush, int32_t options); // GMPI_DrawTextOptions

    int32_t (*getBitmap)(GMPI_IBitmapRenderTarget*, GMPI_IBitmap** returnBitmap);
} GMPI_IBitmapRenderTargetMethods;

// {242DC082-399A-4CAF-8782-878134502F99}
static const GMPI_Guid GMPI_IID_BITMAP_RENDER_TARGET =
{ 0x242DC082, 0x399A, 0x4CAF, { 0x87, 0x82, 0x87, 0x81, 0x34, 0x50, 0x2F, 0x99} };

// INTERFACE 'GMPI_IFactory' (gmpi::drawing::api::IFactory)
//
// IFactory has no derived interface, so appending here cannot break an
// EXISTING binary - but a NEW module calling an appended method on an OLDER
// host runs off the end of that host's vtable. Anything added must be gated
// by probing a new interface guid through queryInterface, never by calling
// and hoping.
struct GMPI_IFactory
{
    struct GMPI_IFactoryMethods* methods;
};

typedef struct GMPI_IFactoryMethods
{
    // Methods of GMPI_IUnknown
    int32_t (*queryInterface)(GMPI_IUnknown*, const GMPI_Guid* iid, void** returnInterface);
    int32_t (*addRef)(GMPI_IUnknown*);
    int32_t (*release)(GMPI_IUnknown*);

    int32_t (*createPathGeometry)(GMPI_IFactory*, GMPI_IPathGeometry** returnPathGeometry);
    int32_t (*createTextFormat)(GMPI_IFactory*, const char* fontFamilyName, int32_t fontWeight, int32_t fontStyle, int32_t fontStretch, float fontHeight, int32_t fontFlags, GMPI_ITextFormat** returnTextFormat); // GMPI_FontWeight, GMPI_FontStyle, GMPI_FontStretch, GMPI_FontFlags
    int32_t (*createImage)(GMPI_IFactory*, int32_t width, int32_t height, int32_t flags, GMPI_IBitmap** returnBitmap);
    int32_t (*loadImageU)(GMPI_IFactory*, const char* uri, GMPI_IBitmap** returnBitmap);
    int32_t (*createStrokeStyle)(GMPI_IFactory*, const GMPI_StrokeStyleProperties* strokeStyleProperties, const float* dashes, int32_t dashesCount, GMPI_IStrokeStyle** returnStrokeStyle);
    int32_t (*getFontFamilyName)(GMPI_IFactory*, int32_t fontIndex, GMPI_IString* returnName);
    int32_t (*getPlatformPixelFormat)(GMPI_IFactory*, int32_t* returnPixelFormat); // GMPI_PixelFormat
    int32_t (*createRichTextFormat)(GMPI_IFactory*, const char* markdownText, float fontHeight, const char* fontFamilyName, int32_t fontFlags, int32_t textAlignment, int32_t paragraphAlignment, int32_t wordWrapping, float lineSpacing, float baseline, GMPI_IRichTextFormat** returnRichTextFormat); // GMPI_FontFlags, GMPI_TextAlignment, GMPI_ParagraphAlignment, GMPI_WordWrapping
    // ref: GMPI_BitmapRenderTargetFlags. dpi has no C-side default; the C++ declaration defaults it to 96.0f, so pass 96.0f for parity.
    int32_t (*createCpuRenderTarget)(GMPI_IFactory*, GMPI_SizeU size, int32_t flags, GMPI_IBitmapRenderTarget** returnBitmapRenderTarget, float dpi);

    // Create a retained, immutable text layout. Base styling is CAPTURED BY
    // VALUE from `baseFormat` - mutating that format afterwards does not
    // affect the layout.
    //
    // runs/runCount may be null/0: a plain-text retained layout, which MUST
    // draw pixel-identically to drawTextU with the same format. runFamilies
    // lists the families runs may select via fontFamilyIndex; an entry that
    // does not resolve renders those runs in the base family - creation never
    // fails for that reason.
    //
    // May return null (GMPI_RETURN_CODE_NO_SUPPORT) on a backend that
    // declines this API; callers are expected to keep their drawTextU path as
    // the fallback. Added last to preserve vtable layout.
    int32_t (*createTextLayout)(GMPI_IFactory*, const char* utf8String, int32_t stringLength, GMPI_ITextFormat* baseFormat, float maxWidth, float maxHeight, const GMPI_TextStyleRun* runs, int32_t runCount, const char* const* runFamilies, int32_t runFamilyCount, GMPI_ITextLayout** returnTextLayout);
} GMPI_IFactoryMethods;

// {D47DEB59-BBA2-4B52-AF12-7983330A8C8A}
static const GMPI_Guid GMPI_IID_FACTORY =
{ 0xD47DEB59, 0xBBA2, 0x4B52, { 0xAF, 0x12, 0x79, 0x83, 0x33, 0x0A, 0x8C, 0x8A} };

#pragma pack(pop)

#endif
